services:
  s3-bucket:
    image: minio/minio:latest
    container_name: s3-bucket
    ports:
      - "9000:9000" # MinIO console/API
      - "9001:9001" # MinIO console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - s3_bucket_data:/data
    command: server /data --console-address ":9001"
  mqtt-consumer:
    build:
      context: ./src/mqtt_consumer
    container_name: mqtt-consumer
    environment:
      NIOTIX_BROKER_URI: ${NIOTIX_BROKER_URI}
      NIOTIX_BROKER_PORT: ${NIOTIX_BROKER_PORT}
      NIOTIX_BROKER_USERNAME: ${NIOTIX_BROKER_USERNAME}
      NIOTIX_BROKER_PASSWORD: ${NIOTIX_BROKER_PASSWORD}
      NIOTIX_BROKER_TOPIC: ${NIOTIX_BROKER_TOPIC}
      S3_HOST: ${S3_HOST_NAME}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
volumes:
  s3_bucket_data:
